server:
  port: 8888

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  application:
    name: java-ssm-swagger

  data:
    redis:
      repositories:
        enabled: false

  redis:
    # 数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
    # 连接超时时间/ms
    timeout: 5000

  #配置jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

#邮箱验证码有效时间/分钟
code:
  expiration: 5


